import 'package:get/get.dart';

class Translator extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar_SY': {
          Keys.password.name: 'كلمة المرور',
          Keys.loginTitle.name: 'قم بتسجيل الدخول لحسابك',
          Keys.email.name: 'بريد الالكتروني',
          Keys.doNotHaveAccount.name: 'لا تمتلك حساب؟',
          Keys.registerNow.name: 'انشئ حساب',
          Keys.login.name: 'تسجيل الدخول',
          Keys.signup.name: 'إنشاء حساب',
          Keys.signupTitle.name: 'أنشئ حساب لبدء الاستخدام',
          Keys.alreadyHaveAccount.name: 'لديك حساب بالفعل؟',
          Keys.personalInfo.name: 'معلومات شخصية',
          Keys.personalInfoTitle.name: 'قبل البدء، نود أن نحصل على مساعدتك',
          Keys.gender.name: ':الجنس',
          Keys.diseaseQuestion.name: 'هل تعاني من أي أمراض ',
          Keys.goalsQuestion.name: 'اختر أهدافك البدنية',
          Keys.goodMorning.name: 'يوما سعيدا',
          Keys.strength.name: ',قوة',
          Keys.health.name: ' صحة',
          Keys.andFitness.name: 'ولياقة',
          Keys.yourGoals.name: 'الاهداف الخاصة بك',
          Keys.next.name: 'التالي',
          Keys.firstName.name: 'الاسم الاول',
          Keys.lastName.name: 'الاسم الاخير',
          Keys.male.name: 'ذكر ',
          Keys.male.name: 'أنثى',
          Keys.birthDate.name: 'تاريخ الميلاد',
          Keys.height.name: 'الوزن',
          Keys.weight.name: 'الطول',
          Keys.selectYourDiseases.name: 'اختر الامراض التي تعاني منها',
          Keys.home.name: 'الرئيسية',
          Keys.messages.name: 'الرسائل',
          Keys.premium.name: 'حصري',
          Keys.notification.name: 'الاشعارات',
          Keys.logOut.name: 'تسجيل خروج',
          Keys.coach.name: 'المدرب',
          Keys.exercies.name: ' تمارين',
          Keys.thisWeek.name: 'هذا الاسبوع ',
        },
        'en_US': {
          Keys.password.name: 'Password',
          Keys.loginTitle.name: 'Log in to your account',
          Keys.email.name: 'Email',
          Keys.doNotHaveAccount.name: 'Don\'t have an account? ',
          Keys.registerNow.name: 'Register now',
          Keys.login.name: 'Log In',
          Keys.signup.name: 'Sign Up',
          Keys.alreadyHaveAccount.name: 'Already Have Account?',
          Keys.signupTitle.name: 'Sign Up to start ',
          Keys.personalInfo.name: 'Personal Info',
          Keys.personalInfoTitle.name:
              'Before start We would love to have your help',
          Keys.gender.name: 'Gender:',
          Keys.diseaseQuestion.name: 'Do you suffer from any diseases?',
          Keys.goalsQuestion.name: 'Choose your goals',
          Keys.goodMorning.name: 'Good Morning',
          Keys.strength.name: 'Strength,',
          Keys.health.name: 'Health ',
          Keys.andFitness.name: ' And Fitness',
          Keys.yourGoals.name: 'Your Goals',
          Keys.next.name: 'Next',
          Keys.firstName.name: 'First Name',
          Keys.lastName.name: 'Last Name',
          Keys.male.name: 'Male',
          Keys.female.name: 'Female',
          Keys.birthDate.name: 'Birth Date',
          Keys.height.name: 'Height',
          Keys.weight.name: 'Weight',
          Keys.selectYourDiseases.name: 'Select Your Diseases',
          Keys.home.name: 'Home',
          Keys.messages.name: 'Messages',
          Keys.premium.name: 'Premium',
          Keys.notification.name: 'Notification',
          Keys.logOut.name: 'LogOut',
          Keys.coach.name: 'Coach',
          Keys.exercies.name: 'Exercies ',
          Keys.thisWeek.name: 'This Week ',
        },
      };
}

enum Keys {
  none,
  password,
  loginTitle,
  email,
  doNotHaveAccount,
  registerNow,
  login,
  signup,
  signupTitle,
  goodMorning,
  strength,
  health,
  andFitness,
  yourGoals,
  alreadyHaveAccount,
  personalInfo,
  personalInfoTitle,
  gender,
  diseaseQuestion,
  goalsQuestion,
  next,
  firstName,
  lastName,
  male,
  female,
  birthDate,
  height,
  weight,
  selectYourDiseases,
  home,
  messages,
  premium,
  notification,
  logOut,
  coach,
  exercies,
  thisWeek
}
